### ISSUE TITLE
To-Do list. 

### ISSUE THREAD

**Issue by AnalogEdition** [AnalogEdition/CSS-RO-Rework#3]
Feel free to add things to this list, or work on anything here. 
- [ ] Look into speedbrake functionality 
- Ferram told me to use the config that stock airbrakes use, unsure how to integrate the module into the part
- [ ] Aero testing split wings and new body flap 
- [ ] Thermal pass for all cfg's
- [ ] Deployable cargo bay radiators
- [x] Tail drag chute
- [x] Fix RCS functionality of engine mount
- [ ] Re-enable ModuleAnimateHeat on SSME?

...and anything else that may peak my fancy along the way.

**Comment by advicedawgg** [comment]
Symmetry is still buggy. The roll problem is still happening. Could be a FAR issue as the control surface seems fixed, nice work!

**Comment by advicedawgg** [comment]
Ok, its definitely an issue with messed up FAR directions on the RIGHT wingset. If you see here: http://i.imgur.com/G1bU8z4.png the lift is reversed, so its coming from inside the body. There must be a way to simply reverse the orientation, then we will have some awesome aero!

**Comment by advicedawgg** [comment]
FIXED!

**Comment by advicedawgg** [comment]
Engine mount has lost its rcs port functionality. Only two ports seem to now function

**Comment by AnalogEdition** [comment]
Looks like this occurred during import to unity. I will need to remodel all 24 transforms.

**Comment by advicedawgg** [comment]
Will need a DRE enabled thermal pass asap, as i cant test re-entry aerodynamics yet, even with thermals more or less turned off in debug, it still overheats.

**Comment by AnalogEdition** [comment]
Added preliminary thermal patch. This is a blanket patch to enable aero reentry testing. Will tweak per part later. IGNORE TEMPERATURE GAUGES. I have no idea what data they actually convey.

**Comment by advicedawgg** [comment]
Adjusted aero. Still needs refining, but it will re-enter fairly well. However will fail if handled improperly

**Comment by AnalogEdition** [comment]
Is it within a plausible margin of error? We don't want it to be too forgiving that you can throw it on max phys warp and walk away. At the same time we don't want to have reload 50 times because we were off a few degrees on aoa and bank angle.
